### PR TITLE
Remove support for order-review, medication-prescribe and order-select CDS Hooks.

### PR DESCRIPTION
**Pull request by plarocque4**

### CODE REVIEW

**Comment by yuliumitre** [comment]
This is cleanup issue. From the settings drop down, it still prompts the removed hooks after I cleaned all the caches and cookies, etc. 

Screen Shot 2020-11-12 at 10 35 14 AM

When using the old hooks, CRD fails silently although the console does show 404. It will be nice to show some error. 
Screen Shot 2020-11-12 at 10 34 15 AM

**Comment by yuliumitre** [comment]
Here are some traces of order-review. Shall we remove them all together? 

16 results - 11 files

SetupGuideForMacOS.md:
  157          "ehr_server": "http://localhost:8080/test-ehr/r4/",
  158:         "cds_service": "http://localhost:8090/r4/cds-services/order-review-crd",
  159          "ehr_server_stu3": "http://localhost:8080/test-ehr/stu3/",
  160:         "cds_service_stu3": "http://localhost:8090/stu3/cds-services/order-review-crd",
  161          "true_base": "http://localhost:8080/test-ehr",

examples/r4/order-review/documentation-required/request_no_prefetch.json:
  3    "fhirServer": "http://localhost:8080/test-ehr/r4/",
  4:   "hook": "order-review",
  5    "user": "Practitioner/example",

examples/r4/order-review/documentation-required/request.json:
  3    "fhirServer": "http://localhost:8080/test-ehr/r4/",
  4:   "hook": "order-review",
  5    "fhirAuthorization": {

examples/r4/order-review/no-documentation-rules/request.json:
  3    "fhirServer": "http://localhost:8080/fhir-server",
  4:   "hook": "order-review",
  5    "fhirAuthorization": {

resources/src/main/java/org/cdshooks/Hook.java:
  8  
  9:   ORDER_REVIEW("order-review"),
  10    MEDICATION_PRESCRIBE("medication-prescribe"),

resources/src/main/java/org/hl7/davinci/r4/crdhook/CrdPrefetch.java:
  10   * Class that supports the representation of prefetch information in a CDS Hook request.
  11:  * It appears that for CRD, prefetch information will be the same, regardless of hook type (order-review,
  12   * medication-prescribe, or order-select).

resources/src/main/java/org/hl7/davinci/stu3/crdhook/CrdPrefetch.java:
  10   * Class that supports the representation of prefetch information in a CDS Hook request.
  11:  * It appears that for CRD, prefetch information will be the same, regardless of hook type (order-review,
  12   * medication-prescribe, or order-select).

resources/src/test/resources/org/hl7/davinci/r4/crdhook/orderreview/requestWithHydratedPrefetchBundle.json:
  1  {
  2:   "hook": "order-review",
  3    "hookInstance": "a4ca4d19-ed2a-491d-87d4-408fefd56ec9",

resources/src/test/resources/org/hl7/davinci/stu3/crdhook/orderreview/requestWithHydratedPrefetchBundle.json:
  1  {
  2:   "hook": "order-review",
  3    "hookInstance": "a4ca4d19-ed2a-491d-87d4-408fefd56ec9",

server/README.md:
  105  | `/cds-services/`                           | CDS Hook Discovery endpoint |
  106: | ~`/cds-services/order-review-crd`~         | CDS Hook endpoint for order-review (deprecated) |
  107  | ~`/cds-services/medication-prescribe-crd`~ | CDS Hook endpoint for medication-prescribe (deprecated) |

server/src/test/java/PrefetchIntegrationTest.java:
  162      JsonNode cards = restTemplate
  163:         .postForObject("http://localhost:" + port + "/r4/cds-services/order-review-crd", entity,
  164              JsonNode.class);

  171      JsonNode cards = restTemplate
  172:         .postForObject("http://localhost:" + port + "/r4/cds-services/order-review-crd", entity,
  173              JsonNode.class);

  181      JsonNode cards = restTemplate
  182:         .postForObject("http://localhost:" + port + "/r4/cds-services/order-review-crd", entity,
  183              JsonNode.class);

  192      JsonNode cards = restTemplate
  193:         .postForObject("http://localhost:" + port + "/r4/cds-services/order-review-crd", entity,
  194              JsonNode.class);

**Comment by plarocque4** [comment]
> Here are some traces of order-review. Shall we remove them all together?
> 
> 16 results - 11 files
> 
> SetupGuideForMacOS.md:
> 157 "ehr_server": "http://localhost:8080/test-ehr/r4/",
> 158: "cds_service": "http://localhost:8090/r4/cds-services/order-review-crd",
> 159 "ehr_server_stu3": "http://localhost:8080/test-ehr/stu3/",
> 160: "cds_service_stu3": "http://localhost:8090/stu3/cds-services/order-review-crd",
> 161 "true_base": "http://localhost:8080/test-ehr",
> 
> examples/r4/order-review/documentation-required/request_no_prefetch.json:
> 3 "fhirServer": "http://localhost:8080/test-ehr/r4/",
> 4: "hook": "order-review",
> 5 "user": "Practitioner/example",
> 
> examples/r4/order-review/documentation-required/request.json:
> 3 "fhirServer": "http://localhost:8080/test-ehr/r4/",
> 4: "hook": "order-review",
> 5 "fhirAuthorization": {
> 
> examples/r4/order-review/no-documentation-rules/request.json:
> 3 "fhirServer": "http://localhost:8080/fhir-server",
> 4: "hook": "order-review",
> 5 "fhirAuthorization": {
> 
> resources/src/main/java/org/cdshooks/Hook.java:
> 8
> 9: ORDER_REVIEW("order-review"),
> 10 MEDICATION_PRESCRIBE("medication-prescribe"),
> 
> resources/src/main/java/org/hl7/davinci/r4/crdhook/CrdPrefetch.java:
> 10 * Class that supports the representation of prefetch information in a CDS Hook request.
> 11: * It appears that for CRD, prefetch information will be the same, regardless of hook type (order-review,
> 12 * medication-prescribe, or order-select).
> 
> resources/src/main/java/org/hl7/davinci/stu3/crdhook/CrdPrefetch.java:
> 10 * Class that supports the representation of prefetch information in a CDS Hook request.
> 11: * It appears that for CRD, prefetch information will be the same, regardless of hook type (order-review,
> 12 * medication-prescribe, or order-select).
> 
> resources/src/test/resources/org/hl7/davinci/r4/crdhook/orderreview/requestWithHydratedPrefetchBundle.json:
> 1 {
> 2: "hook": "order-review",
> 3 "hookInstance": "a4ca4d19-ed2a-491d-87d4-408fefd56ec9",
> 
> resources/src/test/resources/org/hl7/davinci/stu3/crdhook/orderreview/requestWithHydratedPrefetchBundle.json:
> 1 {
> 2: "hook": "order-review",
> 3 "hookInstance": "a4ca4d19-ed2a-491d-87d4-408fefd56ec9",
> 
> server/README.md:
> 105 | `/cds-services/` | CDS Hook Discovery endpoint |
> 106: | ~`/cds-services/order-review-crd`~ | CDS Hook endpoint for order-review (deprecated) |
> 107 | ~`/cds-services/medication-prescribe-crd`~ | CDS Hook endpoint for medication-prescribe (deprecated) |
> 
> server/src/test/java/PrefetchIntegrationTest.java:
> 162 JsonNode cards = restTemplate
> 163: .postForObject("http://localhost:" + port + "/r4/cds-services/order-review-crd", entity,
> 164 JsonNode.class);
> 
> 171 JsonNode cards = restTemplate
> 172: .postForObject("http://localhost:" + port + "/r4/cds-services/order-review-crd", entity,
> 173 JsonNode.class);
> 
> 181 JsonNode cards = restTemplate
> 182: .postForObject("http://localhost:" + port + "/r4/cds-services/order-review-crd", entity,
> 183 JsonNode.class);
> 
> 192 JsonNode cards = restTemplate
> 193: .postForObject("http://localhost:" + port + "/r4/cds-services/order-review-crd", entity,
> 194 JsonNode.class);

Good catch, I'm cleaning all of this up now.

**Comment by plarocque4** [comment]
> This is cleanup issue. From the settings drop down, it still prompts the removed hooks after I cleaned all the caches and cookies, etc.
> 
> Screen Shot 2020-11-12 at 10 35 14 AM
> 
> When using the old hooks, CRD fails silently although the console does show 404. It will be nice to show some error.
> Screen Shot 2020-11-12 at 10 34 15 AM

The first screenshot issue with the old options looks like some kind of browser cache issue. On my machine in Chrome I don't get a drop down with any options at all.

The second issue I believe is working as designed. I believe that since there is no support for that hook we reply with a standard HTML 404 code saying resource is not available. It is not listed as an option when querying for support, so I don't think we have to handle it.

**Comment by yuliumitre** [comment]
@plarocque4 Hook.java has the last trace of order-review :-) 

https://github.com/HL7-DaVinci/CRD/blob/27345827d6a6a53f3bcbb254a82b89b34551e0df/resources/src/main/java/org/cdshooks/Hook.java

**Comment by plarocque4** [comment]
> @plarocque4 Hook.java has the last trace of order-review :-)
> 
> https://github.com/HL7-DaVinci/CRD/blob/27345827d6a6a53f3bcbb254a82b89b34551e0df/resources/src/main/java/org/cdshooks/Hook.java

These are in the resources section. I did not end up removing the other types of hooks from here. If you look in the resources/src/main/java/org/hl7/davinci/r4/crdhook folder you will still see the other hooks. The server code however does not make use of it. These are like a library of possible types to use. I don't think we need to remove them but I could be persuaded if everyone thinks it is necessary.

**Comment by yuliumitre** [comment]
Got it. Can you add some comments in the resource for Hook, e.g. CRD only supports order-sign? Thanks.

**Review by yuliumitre — APPROVED** [review]
Great, thanks.

**Pull request merged**
