### PR TITLE
Preemptive prior auth

### PR DESCRIPTION
**Pull request by plarocque4**
Add support for preemptive prior auth.

To test you must include the changes for the crd-request-generator in the preemptive-prior-auth branch as well as the CDS-Library in the preemptive-prior-auth branch. Choose Theodor Roosevelt and G0180 Service Request for Medicare-covered home health services under a home health plan of care.

### CODE REVIEW

**Review by KeeyanGhoreshi — APPROVED** [review]
Looks good to me

**Comment by yuliumitre** [comment]
The PR works well. Have a question about those two buttons after the preemptive prior-auth is granted: the first time I clicked the buttons, it works well. I am wondering if the clicking order matters? As adding prior-auth to Request is using a reference? Does it need to store the ClaimResponse first, then you can add it to the order? 

After the first submit, then clicked the two buttons, those two buttons are disabled. Then I submitted the same request, those two buttons remain disabled although the prios-auth GUID is different. I am wondering if this is a valid use case. If not, it will probably better reenable the buttons after submit?

**Review by RobertScalfani — APPROVED** [review]

**Comment by plarocque4** [comment]
> The PR works well. Have a question about those two buttons after the preemptive prior-auth is granted: the first time I clicked the buttons, it works well. I am wondering if the clicking order matters? As adding prior-auth to Request is using a reference? Does it need to store the ClaimResponse first, then you can add it to the order?
> 
> After the first submit, then clicked the two buttons, those two buttons are disabled. Then I submitted the same request, those two buttons remain disabled although the prios-auth GUID is different. I am wondering if this is a valid use case. If not, it will probably better reenable the buttons after submit?

I'll need to fix the request generator to handle these problems. When one of these suggestions is clicked, the other should gray out. They should also both be available as options again after the new CRD request CARD response is received.

**Comment by yuliumitre** [comment]
> > The PR works well. Have a question about those two buttons after the preemptive prior-auth is granted: the first time I clicked the buttons, it works well. I am wondering if the clicking order matters? As adding prior-auth to Request is using a reference? Does it need to store the ClaimResponse first, then you can add it to the order?
> > After the first submit, then clicked the two buttons, those two buttons are disabled. Then I submitted the same request, those two buttons remain disabled although the prios-auth GUID is different. I am wondering if this is a valid use case. If not, it will probably better reenable the buttons after submit?
> 
> I'll need to fix the request generator to handle these problems. When one of these suggestions is clicked, the other should gray out. They should also both be available as options again after the new CRD request CARD response is received.

Sounds good. Go ahead and merge this PR. Thanks.

**Review by yuliumitre — APPROVED** [review]

**Comment by plarocque4** [comment]
> > > The PR works well. Have a question about those two buttons after the preemptive prior-auth is granted: the first time I clicked the buttons, it works well. I am wondering if the clicking order matters? As adding prior-auth to Request is using a reference? Does it need to store the ClaimResponse first, then you can add it to the order?
> > > After the first submit, then clicked the two buttons, those two buttons are disabled. Then I submitted the same request, those two buttons remain disabled although the prios-auth GUID is different. I am wondering if this is a valid use case. If not, it will probably better reenable the buttons after submit?
> > 
> > 
> > I'll need to fix the request generator to handle these problems. When one of these suggestions is clicked, the other should gray out. They should also both be available as options again after the new CRD request CARD response is received.
> 
> Sounds good. Go ahead and merge this PR. Thanks.

I made some changes to this branch to add in missing values in the Action, Suggestion, and Card. Please review these new changes!

**Review by yuliumitre — APPROVED** [review]
It works well. I can see the flag is added to the card.

**Pull request merged**
