### PR TITLE
DMEERX-739 - update capability statement for order-sign and order-select

### PR DESCRIPTION
**Pull request by lpdecelles**
Added order-sign and order-select to capability statement

### CODE REVIEW

**Comment by plarocque4** [comment]
I think we need to update the capability statement for STU3 as well.

**Comment by plarocque4** [comment]
I feel silly for missing this, thanks for fixing!

**Comment by lpdecelles** [comment]
@plarocque4 did we do this STU 3 also?

**Comment by plarocque4** [comment]
> @plarocque4 no worries, it not a big deal. Did we do this STU 3 also?

Yes, we support all four of them for STU3 as well.

**Comment by lpdecelles** [comment]
I have made the same fix for STU 3

**Pull request merged**
