### PR TITLE
Hbcrdrules

### PR DESCRIPTION
**Pull request by yuliumitre**
Update CRD rules for hospital beds order.

### CODE REVIEW

**Comment by lpdecelles** [comment]
image

Yolanda we think this is failing because of a "text string" in the CI test. You can run these with this: "gradle clean check" which is part of the readme see the failure.

**Comment by yuliumitre** [comment]
I will take a look at the issues.

**Comment by lpdecelles** [comment]
It might be that we need to change the test(s). Maybe to not be as strict.

**Comment by yuliumitre** [comment]
@lpdecelles The test has been fixed.

**Comment by lpdecelles** [comment]
image

This looks good a card is returned.

**Pull request merged**
