### PR TITLE
Crd log

### PR DESCRIPTION
**Pull request by hkong**
CRD log page now displays info about requests
also updated react and other JS libraries to remove vulnerabilities reported by NPM

### CODE REVIEW

**Comment by lpdecelles** [comment]
Hello Howard,

This PR has conflicts.

Larry

**Comment by hkong** [comment]
They should be fixed now.

**Comment by lpdecelles** [comment]
image

Howard, as I mentioned I am seeing blank screen when trying launch DTR.

**Comment by hkong** [comment]
New merge—it looks like there was a new push just before I merged earlier, let's try it again.  I was able to verify what you showed me in your office now works.

**Comment by lpdecelles** [comment]
Unit tested with E0424 R4 CRD and DTR end-to-end. Looks good. "CQL Results" link does not work. Will open another Jira ticket for this.

**Comment by hkong** [comment]
Thanks, Larry, I meant to open that as a separate Jira ticket

**Comment by lpdecelles** [comment]
I just opened a Jira ticket for this. "CQL Results" link does not work.

**Pull request merged**
